### ISSUE TITLE
Scripts for each step

### ISSUE THREAD

**Issue by dlorenc** [sigstore/root-signing-practice#65]
step0.sh: setup environment
step1.sh: add keys
step1.5.sh: combine keys
step2.sh: sign root/targets
step3.sh sign snapshot
step4.sh sign timestamp

**Comment by asraa** [comment]
we could also scriptify the verifies

instead of having to fetch pull requests, just do something like

verify.sh <PULLID> (which will also cleanup git state)

**Comment by asraa** [comment]
I think this is done now with the verification script in
